# ===================================
#  Form Behavior Config
# ===================================

name: Hello
form: ~/Modules/Abc/Models/Hello/fields.yaml
modelClass: Modules\Abc\Models\Hello
defaultRedirect: abc/hello

create:
    redirect: abc/hello/update/:id
    redirectClose: abc/hello

update:
    redirect: abc/hello
    redirectClose: abc/hello
