# ===================================
#  Relation Behavior Config
# ===================================

worlds:
    label: 世界
    readOnly: true
    view:
      list: ~/Modules/Hello/Models/world/columns.yaml
      showSearch: true
      # recordsPerPage: 5

    manage:
        form: ~/Modules/Hello/Models/world/fields.yaml
        context: relation
categories:
    label: 分类
    list: ~/Modules/Hello/Models/category/columns.yaml
    form: ~/Modules/Hello/Models/category/fields.yaml
    readOnly: true
    view:
      showSearch: true
      recordsPerPage: 5

    manage:
        context: relation
